### ISSUE TITLE
new padAngle options for donut & pie type

### ISSUE THREAD

**Issue by netil** [c3js/c3#1920]
Current version don't have option for padding in donut/pie types.
For this reason, many uses css style hack setting `stroke` prop values.

```css
.c3-chart-arcs .c3-arc { stroke-width: 5px; stroke: #fff; }
```

But, in that case, there's no way to style border color differently than element's background(fill).

I'm suggesting support new `padAngle` options for donut/pie, which the option will be illustrated as below.
```js
donut : {
    padAngle: 0.04,
},
pie: {
    padAngle: 0.05
}
```
