### ISSUE TITLE
How to hide data labels text

### ISSUE THREAD

**Issue by LeoPerez28** [c3js/c3#1925]
Hi!
Can you help me how i can hide data label text.
already set it to true, but i want to hide it to a certain screen size.
i want to hide it by a function without loading again all the data.

Chart.data.labels.hide();
or doing it on the style.
cant figure out how to do this.

Thanks in advance..

**Comment by LeoPerez28** [comment]
hi, just want to share.
I solved the issue by adding the condition to the label function. working just fine, just dint get the exact plan "to hide when resized".
          labels: {
            format: function (v, id, i, j) { 
              if (w >= 1366) {
              return v.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ","); 
              };
            },
          },
w is the width.
this was suppose to be done in windows change event  but cant get the right code.

hoping this someday helps  someone newbie like me.. :-)

Thanks c3js,. :-)

**Comment by netil** [comment]
@LeoPerez28, just set media query rule for that.

```css
/* Will hide data label texts when screen size is up to 1366px */
@media (min-width: 1366px) {
    .c3-chart-texts .c3-text {
        display: none;
    }
}
```
