### ISSUE TITLE
Donut chart labels overlaping/cutting

### ISSUE THREAD

**Issue by DinakaranS** [c3js/c3#1960]
Hi,

I am using donut chart to display high number values. But its overlapping/cutting and looks ugly, is there any way to fix this.
<img width="314" alt="screen shot 2017-02-10 at 5 59 34 pm" src="https://cloud.githubusercontent.com/assets/8424594/22826921/0bc51bb2-efbb-11e6-9146-4f1b1e5e7e65.png">

**Comment by netil** [comment]
One approach will be styling texts

```css
.c3-chart-arcs g text {
    font-size: 10px;
}
```
