### ISSUE TITLE
Can we set the color of the axis?

### ISSUE THREAD

**Issue by panubear** [c3js/c3#210]
Hi, Is there any way to set the color of X & Y axis? I find that we could set the tick text and text label from c3.css but I don't know how to change the color of axis reference line.
![color](https://cloud.githubusercontent.com/assets/6915603/2876734/f180468e-d43b-11e3-9ec5-ecebd80266ea.jpg)

**Comment by ComradeKeys** [comment]
Thank you for saving my ass

**Comment by ceremcem** [comment]
Here is my current `css` to style axis, ticks and the legend text: 

```css
.inverted .c3 .c3-axis-x path,
.inverted .c3 .c3-axis-x line,

.inverted .c3 .c3-axis-y path,
.inverted .c3 .c3-axis-y line {
    stroke: white;
}

.inverted .c3 .c3-axis-x g,
.inverted .c3 .c3-axis-y g,
.inverted .c3 .c3-legend-item-data text {
    fill: whitesmoke;
}
```
