### ISSUE TITLE
Update to 0.1.35, bar graph no longer renders?

### ISSUE THREAD

**Issue by jsec** [c3js/c3#217]
I have a simple bar chart that displays dynamic data (populated by an EmberJS app). Upon updating to 0.1.35, the chart no long renders.

Chart setup: 

```
init: ->
  @_super()
  @isResponsive ?= true

afterRenderEvent: ->
  @bindId = "#" + @$().attr('id')

  config = @getConfig()
  config.bindto = @bindId

  @chart = c3.generate(config)

  getConfig: ->
    config =
      size:
        height: @height ? undefined
        width: @width ? undefined
      data:
        x: @xField
        columns: @get('mappedData')
        type: 'bar'
        labels: false
      bar:
        width:
          ratio: 0.5
      axis:
        x:
          type: 'categorized'
        y:
          padding:
            top: 100
            bottom: 100
        rotated: @isRotated ? false
      color:
        pattern: @colors ? []
      legend:
        show: false

    return config
```

And this is the error that is getting returned:
![image](https://cloud.githubusercontent.com/assets/782969/2892111/31e13e7e-d539-11e3-8809-d8d6615872a5.png

It looks like the chart is trying to render before any data is returned, but this was never a problem before.
