### ISSUE TITLE
Scatter type doesn't show the labels

### ISSUE THREAD

**Issue by omarcho** [c3js/c3#481]
In spite of line types shows labels, scatter type doesn't show it.
A workaround is possible by using line and changing css:

```css
# chart-id .c3-line {
  stroke-width: 0px;
}
```

I'm not sure if it is an error.
